# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(240, 320)
        self.screen = QtGui.QLabel(Form)
        self.screen.setGeometry(QtCore.QRect(0, 60, 240, 240))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.screen.sizePolicy().hasHeightForWidth())
        self.screen.setSizePolicy(sizePolicy)
        self.screen.setAutoFillBackground(False)
        self.screen.setText(_fromUtf8(""))
        self.screen.setTextFormat(QtCore.Qt.AutoText)
        self.screen.setScaledContents(False)
        self.screen.setObjectName(_fromUtf8("screen"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 300, 240, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet(_fromUtf8("background-color: rgb(42, 40, 38);\n"
"color:rgb(255,255,255);"))
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lcdNumber = QtGui.QLCDNumber(Form)
        self.lcdNumber.setGeometry(QtCore.QRect(20, 0, 81, 31))
        self.lcdNumber.setStyleSheet(_fromUtf8("color:rgb(255,255,255);"))
        self.lcdNumber.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setNumDigits(10)
        self.lcdNumber.setMode(QtGui.QLCDNumber.Dec)
        self.lcdNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber.setProperty("value", 127.23913143)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.lcdNumber_2 = QtGui.QLCDNumber(Form)
        self.lcdNumber_2.setGeometry(QtCore.QRect(20, 30, 81, 31))
        self.lcdNumber_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber_2.setStyleSheet(_fromUtf8("color:rgb(255,255,255);"))
        self.lcdNumber_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdNumber_2.setSmallDecimalPoint(False)
        self.lcdNumber_2.setNumDigits(10)
        self.lcdNumber_2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_2.setProperty("value", 45.762581)
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 21, 31))
        self.label_3.setStyleSheet(_fromUtf8("color:rgb(255,255,255);"))
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(0, 30, 21, 31))
        self.label_4.setStyleSheet(_fromUtf8("color:rgb(255,255,255);"))
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 240, 60))
        self.label_5.setStyleSheet(_fromUtf8("background-color: rgb(42, 40, 38);"))
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(100, 0, 21, 31))
        self.label_6.setStyleSheet(_fromUtf8("color:rgb(255,255,255);"))
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setScaledContents(False)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(154, 0, 21, 31))
        self.label_7.setStyleSheet(_fromUtf8("color:rgb(255,255,255);"))
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setScaledContents(False)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lcdNumber_3 = QtGui.QLCDNumber(Form)
        self.lcdNumber_3.setGeometry(QtCore.QRect(110, 0, 41, 31))
        self.lcdNumber_3.setStyleSheet(_fromUtf8("color:rgb(255,255,255);"))
        self.lcdNumber_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdNumber_3.setLineWidth(1)
        self.lcdNumber_3.setSmallDecimalPoint(False)
        self.lcdNumber_3.setNumDigits(5)
        self.lcdNumber_3.setMode(QtGui.QLCDNumber.Dec)
        self.lcdNumber_3.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_3.setProperty("value", 88888.0)
        self.lcdNumber_3.setProperty("intValue", 88888)
        self.lcdNumber_3.setObjectName(_fromUtf8("lcdNumber_3"))
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(100, 30, 21, 31))
        self.label_8.setStyleSheet(_fromUtf8("color:rgb(255,255,255);"))
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setScaledContents(False)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lcdNumber_5 = QtGui.QLCDNumber(Form)
        self.lcdNumber_5.setGeometry(QtCore.QRect(110, 30, 41, 31))
        self.lcdNumber_5.setStyleSheet(_fromUtf8("color:rgb(255,255,255);"))
        self.lcdNumber_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdNumber_5.setLineWidth(1)
        self.lcdNumber_5.setSmallDecimalPoint(False)
        self.lcdNumber_5.setNumDigits(5)
        self.lcdNumber_5.setMode(QtGui.QLCDNumber.Dec)
        self.lcdNumber_5.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_5.setProperty("value", 88888.0)
        self.lcdNumber_5.setProperty("intValue", 88888)
        self.lcdNumber_5.setObjectName(_fromUtf8("lcdNumber_5"))
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(154, 30, 21, 31))
        self.label_9.setStyleSheet(_fromUtf8("color:rgb(255,255,255);"))
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setScaledContents(False)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.text_NP = QtGui.QLabel(Form)
        self.text_NP.setGeometry(QtCore.QRect(202, 30, 21, 31))
        self.text_NP.setStyleSheet(_fromUtf8("color:rgb(255,255,255);"))
        self.text_NP.setTextFormat(QtCore.Qt.AutoText)
        self.text_NP.setScaledContents(False)
        self.text_NP.setObjectName(_fromUtf8("text_NP"))
        self.lcdNumber_6 = QtGui.QLCDNumber(Form)
        self.lcdNumber_6.setGeometry(QtCore.QRect(175, 30, 16, 31))
        self.lcdNumber_6.setStyleSheet(_fromUtf8("color:rgb(255,255,255);"))
        self.lcdNumber_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdNumber_6.setSmallDecimalPoint(False)
        self.lcdNumber_6.setNumDigits(2)
        self.lcdNumber_6.setMode(QtGui.QLCDNumber.Dec)
        self.lcdNumber_6.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_6.setProperty("value", 13.0)
        self.lcdNumber_6.setProperty("intValue", 13)
        self.lcdNumber_6.setObjectName(_fromUtf8("lcdNumber_6"))
        self.lcdNumber_7 = QtGui.QLCDNumber(Form)
        self.lcdNumber_7.setGeometry(QtCore.QRect(220, 30, 16, 31))
        self.lcdNumber_7.setStyleSheet(_fromUtf8("color:rgb(255,255,255);"))
        self.lcdNumber_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdNumber_7.setSmallDecimalPoint(False)
        self.lcdNumber_7.setNumDigits(2)
        self.lcdNumber_7.setMode(QtGui.QLCDNumber.Dec)
        self.lcdNumber_7.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_7.setProperty("value", 13.0)
        self.lcdNumber_7.setProperty("intValue", 13)
        self.lcdNumber_7.setObjectName(_fromUtf8("lcdNumber_7"))
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 20, 240, 20))
        self.line.setStyleSheet(_fromUtf8("color:rgb(100,100,100);"))
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(96, 0, 3, 61))
        self.line_2.setStyleSheet(_fromUtf8("color:rgb(100,100,100);"))
        self.line_2.setFrameShadow(QtGui.QFrame.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(150, 0, 3, 61))
        self.line_3.setStyleSheet(_fromUtf8("color:rgb(100,100,100);"))
        self.line_3.setFrameShadow(QtGui.QFrame.Plain)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(185, 0, 20, 61))
        self.line_4.setStyleSheet(_fromUtf8("color:rgb(100,100,100);"))
        self.line_4.setFrameShadow(QtGui.QFrame.Plain)
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.lcdNumber_8 = QtGui.QLCDNumber(Form)
        self.lcdNumber_8.setGeometry(QtCore.QRect(165, 0, 31, 31))
        self.lcdNumber_8.setStyleSheet(_fromUtf8("color:rgb(255,255,255);"))
        self.lcdNumber_8.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdNumber_8.setLineWidth(1)
        self.lcdNumber_8.setSmallDecimalPoint(False)
        self.lcdNumber_8.setNumDigits(4)
        self.lcdNumber_8.setMode(QtGui.QLCDNumber.Dec)
        self.lcdNumber_8.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_8.setProperty("value", 88888.0)
        self.lcdNumber_8.setProperty("intValue", 88888)
        self.lcdNumber_8.setObjectName(_fromUtf8("lcdNumber_8"))
        self.text_Sat = QtGui.QLabel(Form)
        self.text_Sat.setGeometry(QtCore.QRect(202, 0, 21, 31))
        self.text_Sat.setStyleSheet(_fromUtf8("color:rgb(255,255,255);"))
        self.text_Sat.setTextFormat(QtCore.Qt.AutoText)
        self.text_Sat.setScaledContents(False)
        self.text_Sat.setObjectName(_fromUtf8("text_Sat"))
        self.lcdNumber_9 = QtGui.QLCDNumber(Form)
        self.lcdNumber_9.setGeometry(QtCore.QRect(220, 0, 16, 31))
        self.lcdNumber_9.setStyleSheet(_fromUtf8("color:rgb(255,255,255);"))
        self.lcdNumber_9.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdNumber_9.setSmallDecimalPoint(False)
        self.lcdNumber_9.setNumDigits(2)
        self.lcdNumber_9.setMode(QtGui.QLCDNumber.Dec)
        self.lcdNumber_9.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_9.setProperty("value", 13.0)
        self.lcdNumber_9.setProperty("intValue", 13)
        self.lcdNumber_9.setObjectName(_fromUtf8("lcdNumber_9"))
        self.line_5 = QtGui.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(0, 50, 240, 20))
        self.line_5.setStyleSheet(_fromUtf8("color:rgb(100,100,100);"))
        self.line_5.setFrameShadow(QtGui.QFrame.Plain)
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(Form)
        self.line_6.setGeometry(QtCore.QRect(0, 290, 240, 20))
        self.line_6.setStyleSheet(_fromUtf8("color:rgb(100,100,100);"))
        self.line_6.setFrameShadow(QtGui.QFrame.Plain)
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.label_5.raise_()
        self.label_2.raise_()
        self.lcdNumber.raise_()
        self.lcdNumber_2.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.lcdNumber_3.raise_()
        self.label_8.raise_()
        self.lcdNumber_5.raise_()
        self.label_9.raise_()
        self.text_NP.raise_()
        self.lcdNumber_6.raise_()
        self.lcdNumber_7.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.screen.raise_()
        self.lcdNumber_8.raise_()
        self.text_Sat.raise_()
        self.lcdNumber_9.raise_()
        self.line_5.raise_()
        self.line_6.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_2.setText(_translate("Form", "Done!", None))
        self.label_3.setText(_translate("Form", "Lng", None))
        self.label_4.setText(_translate("Form", "Lat", None))
        self.label_6.setText(_translate("Form", "NT", None))
        self.label_7.setText(_translate("Form", "Ang", None))
        self.label_8.setText(_translate("Form", "T", None))
        self.label_9.setText(_translate("Form", "NS", None))
        self.text_NP.setText(_translate("Form", "NP", None))
        self.text_Sat.setText(_translate("Form", "Sat", None))

